# Generated by Django 5.1.5 on 2025-04-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Us',
            new_name='AboutUs',
        ),
    ]
